/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Blazebit
 */
package com.blazebit.query.connector.aws.iam;

import software.amazon.awssdk.services.iam.model.AttachedPolicy;
import software.amazon.awssdk.services.iam.model.GetAccountSummaryResponse;
import software.amazon.awssdk.services.iam.model.Group;
import software.amazon.awssdk.services.iam.model.MFADevice;
import software.amazon.awssdk.services.iam.model.PasswordPolicy;
import software.amazon.awssdk.services.iam.model.Role;
import software.amazon.awssdk.services.iam.model.ServerCertificateMetadata;
import software.amazon.awssdk.services.iam.model.SummaryKeyType;
import software.amazon.awssdk.services.iam.model.User;
import software.amazon.awssdk.services.iam.model.VirtualMFADevice;

import java.time.Instant;
import java.util.Collections;
import java.util.List;
import java.util.Map;

public final class TestObjects {

	private TestObjects() {
	}

	public static AwsIamUser userWithMfa() {
		User user = User.builder()
				.path( "/" )
				.userName( "userWithMFA" )
				.userId( "AIDAJDPLRKL123123" )
				.arn( "arn:aws:iam::123456789012:user/userWithMFA" )
				.createDate( Instant.parse( "2024-07-15T12:41:28+00:00" ) )
				.passwordLastUsed( Instant.parse( "2024-07-15T12:41:28+00:00" ) )
				.build();
		return new AwsIamUser( "123", user.userId(), user );
	}

	public static AwsIamRole role() {
		Role role = Role.builder()
				.path( "/" )
				.roleName( "TestRole" )
				.roleId( "AIDAIRLTEST123123" )
				.arn( "arn:aws:iam::123456789012:role/TestRole" )
				.createDate( Instant.parse( "2024-07-15T12:41:28+00:00" ) )
				.build();
		return new AwsIamRole( "123", role.roleId(), role );
	}

	public static AwsIamMfaDevice mfaDevice() {
		MFADevice mfaDevice = MFADevice.builder()
				.userName( "userWithMFA" )
				.serialNumber( "arn:aws:iam::123456789012:mfa/test" )
				.enableDate( Instant.parse( "2024-07-15T12:41:28+00:00" ) )
				.build();
		return new AwsIamMfaDevice( "123", mfaDevice.serialNumber(), mfaDevice );
	}

	public static List<AwsIamPasswordPolicy> defaultAccountPasswordPolicy() {
		PasswordPolicy passwordPolicy = PasswordPolicy.builder()
				.minimumPasswordLength( 8 )
				.requireSymbols( false )
				.requireNumbers( false )
				.requireUppercaseCharacters( true )
				.requireLowercaseCharacters( true )
				.allowUsersToChangePassword( true )
				.maxPasswordAge( 90 )
				.passwordReusePrevention( 5 )
				.hardExpiry( false )
				.build();
		return Collections.singletonList( new AwsIamPasswordPolicy( "123", passwordPolicy ) );
	}

	// Data generated by AWS Cli:
	// $aws iam get-account-summary --profile admindev
	public static AwsIamAccountSummary accountSummary() {
		var test =
				GetAccountSummaryResponse.builder()
						.summaryMap(
								Map.ofEntries(
										Map.entry( SummaryKeyType.GROUP_POLICY_SIZE_QUOTA, 0 ),
										Map.entry( SummaryKeyType.POLICIES, 0 ),
										Map.entry( SummaryKeyType.GROUPS_PER_USER_QUOTA, 0 ),
										Map.entry( SummaryKeyType.ATTACHED_POLICIES_PER_USER_QUOTA, 0 ),
										Map.entry( SummaryKeyType.USERS, 5 ),
										Map.entry( SummaryKeyType.POLICIES_QUOTA, 10 ),
										Map.entry( SummaryKeyType.ACCOUNT_MFA_ENABLED, 1 ),
										Map.entry( SummaryKeyType.ACCESS_KEYS_PER_USER_QUOTA, 2 ),
										Map.entry( SummaryKeyType.POLICY_VERSIONS_IN_USE_QUOTA, 3 ),
										Map.entry( SummaryKeyType.GLOBAL_ENDPOINT_TOKEN_VERSION, 2 ),
										Map.entry( SummaryKeyType.VERSIONS_PER_POLICY_QUOTA, 1 ),
										Map.entry( SummaryKeyType.ATTACHED_POLICIES_PER_GROUP_QUOTA, 2 ),
										Map.entry( SummaryKeyType.POLICY_SIZE_QUOTA, 0 ),
										Map.entry( SummaryKeyType.GROUPS, 3 ),
										Map.entry( SummaryKeyType.ACCOUNT_SIGNING_CERTIFICATES_PRESENT, 0 ),
										Map.entry( SummaryKeyType.USERS_QUOTA, 6 ),
										Map.entry( SummaryKeyType.SERVER_CERTIFICATES_QUOTA, 3 ),
										Map.entry( SummaryKeyType.MFA_DEVICES, 1 ),
										Map.entry( SummaryKeyType.USER_POLICY_SIZE_QUOTA, 2 ),
										Map.entry( SummaryKeyType.POLICY_VERSIONS_IN_USE, 2 ),
										Map.entry( SummaryKeyType.SERVER_CERTIFICATES, 3 ),
										Map.entry( SummaryKeyType.SIGNING_CERTIFICATES_PER_USER_QUOTA, 2 ),
										Map.entry( SummaryKeyType.MFA_DEVICES_IN_USE, 1 ),
										Map.entry( SummaryKeyType.ATTACHED_POLICIES_PER_ROLE_QUOTA, 2 ),
										Map.entry( SummaryKeyType.ACCOUNT_ACCESS_KEYS_PRESENT, 1 ),
										Map.entry( SummaryKeyType.GROUPS_QUOTA, 5 ) ) )
						.build();
		return new AwsIamAccountSummary( "123", test.summaryMap() );
	}

	public static AwsIamUserAttachedPolicy userAttachedPolicy() {
		AttachedPolicy attachedPolicy = AttachedPolicy.builder()
				.policyName( "ReadOnlyAccess" )
				.policyArn( "arn:aws:iam::aws:policy/ReadOnlyAccess" )
				.build();
		return AwsIamUserAttachedPolicy.from( "123", "userWithMFA", attachedPolicy );
	}

	public static AwsIamUserInlinePolicy userInlinePolicy() {
		String policyDocument = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"s3:GetObject\",\"Resource\":\"arn:aws:s3:::example-bucket/*\"}]}";
		return AwsIamUserInlinePolicy.fromJson( "123", "userWithMFA", "AllowS3Read", policyDocument );
	}

	public static AwsIamVirtualMfaDevice virtualMfaDeviceForRoot() {
		VirtualMFADevice virtualMFADevice = VirtualMFADevice.builder()
				.serialNumber( "arn:aws:iam::123456789012:mfa/root-account-mfa-device" )
				.enableDate( Instant.parse( "2024-07-15T12:41:28+00:00" ) )
				.build();
		return new AwsIamVirtualMfaDevice( "123", virtualMFADevice.serialNumber(), virtualMFADevice );
	}

	public static AwsIamVirtualMfaDevice virtualMfaDeviceForUser() {
		User user = User.builder()
				.arn( "arn:aws:iam::123456789012:user/userWithMFA" )
				.build();
		VirtualMFADevice virtualMFADevice = VirtualMFADevice.builder()
				.serialNumber( "arn:aws:iam::123456789012:mfa/userWithMFA" )
				.user( user )
				.enableDate( Instant.parse( "2024-07-15T12:41:28+00:00" ) )
				.build();
		return new AwsIamVirtualMfaDevice( "123", virtualMFADevice.serialNumber(), virtualMFADevice );
	}

	public static AwsIamGroup group() {
		Group group = Group.builder()
				.path( "/" )
				.groupName( "SupportTeam" )
				.groupId( "AIDAGROUPTEST123123" )
				.arn( "arn:aws:iam::123456789012:group/SupportTeam" )
				.createDate( Instant.parse( "2024-07-15T12:41:28+00:00" ) )
				.build();
		return new AwsIamGroup( "123", group.groupId(), group );
	}

	public static AwsIamGroupAttachedPolicy groupAttachedPolicy() {
		AttachedPolicy attachedPolicy = AttachedPolicy.builder()
				.policyName( "AWSSupportAccess" )
				.policyArn( "arn:aws:iam::aws:policy/AWSSupportAccess" )
				.build();
		return AwsIamGroupAttachedPolicy.from( "123", "SupportTeam", attachedPolicy );
	}

	public static AwsIamRoleAttachedPolicy roleAttachedPolicy() {
		AttachedPolicy attachedPolicy = AttachedPolicy.builder()
				.policyName( "AWSSupportAccess" )
				.policyArn( "arn:aws:iam::aws:policy/AWSSupportAccess" )
				.build();
		return AwsIamRoleAttachedPolicy.from( "123", "SupportRole", attachedPolicy );
	}

	public static AwsIamGroupMembership groupMembership() {
		User user = User.builder()
				.userName( "userWithMFA" )
				.arn( "arn:aws:iam::123456789012:user/userWithMFA" )
				.build();
		return AwsIamGroupMembership.from( "123", "SupportTeam", user );
	}

	public static AwsIamServerCertificate serverCertificate() {
		ServerCertificateMetadata metadata = ServerCertificateMetadata.builder()
				.path( "/" )
				.serverCertificateName( "TestCertificate" )
				.serverCertificateId( "ASCAJDPLRKL123123" )
				.arn( "arn:aws:iam::123456789012:server-certificate/TestCertificate" )
				.uploadDate( Instant.parse( "2024-01-15T12:41:28+00:00" ) )
				.expiration( Instant.parse( "2025-01-15T12:41:28+00:00" ) )
				.build();
		return new AwsIamServerCertificate( "123", metadata.serverCertificateId(), metadata );
	}
}
